Disable Architectury API where a Forge port does not exist
architectury/template-generator pull request #25
Opened 2024-12-04 06:13 UTC by cassiancc

This is a PR to improve #19 by adding support for disabling Architectury API on versions of LexForge where Architectury API is not available.

2024-12-06 18:09 UTC, Juuxel requested changes
The change itself looks good 👍 

Please follow the existing code format (semicolons at the end of the line and `} else {` on one line).

2024-12-06 18:09 UTC, Juuxel commented on res/script.js
> +    console.log(isArchitecturyApiAvailable())
```suggestion
```
This shouldn't be kept in production.

2024-12-06 18:09 UTC, Juuxel commented on src/web.rs
> +            .await
Please keep the existing code intact

2024-12-06 18:09 UTC, Juuxel commented on src/web.rs
> +        Ok(game_version.forge_major_version().expect("No forge version available!").parse::<i32>().unwrap() < 50)
```suggestion
        Ok(game_version.forge_major_version().unwrap().parse::<i32>().unwrap() < 50)
```
You already know that it's available so `unwrap` is fine

2024-12-06 18:24 UTC, cassiancc commented
Code format changes should now be resolved. Thanks for the feedback.

2025-05-06 22:07 UTC, Juuxel approved these changes
Thanks for the patch, looks good now.

2025-05-06 22:07 UTC, merged